// Do not edit. This file is machine generated by the Resource DLL Wizard.

library SASPlanet;

{$R *.RES}
{ITE} {LCID:00000419:000004809} {}
{ITE} {DFMFileType} {vcl\DBLOGDLG.dfm}
{ITE} {DFMFileType} {vcl\DBPWDLG.dfm}
{ITE} {DFMFileType} {u_MarksDb.dfm}
{ITE} {DFMFileType} {UAbout.dfm}
{ITE} {DFMFileType} {UAddCategory.dfm}
{ITE} {DFMFileType} {UaddLine.dfm}
{ITE} {DFMFileType} {UaddPoint.dfm}
{ITE} {DFMFileType} {UaddPoly.dfm}
{ITE} {DFMFileType} {Ubrowser.dfm}
{ITE} {DFMFileType} {UEditMap.dfm}
{ITE} {DFMFileType} {UFDGAvailablePic.dfm}
{ITE} {DFMFileType} {UImport.dfm}
{ITE} {DFMFileType} {ULogo.dfm}
{ITE} {DFMFileType} {UMarksExplorer.dfm}
{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit4.dfm}
{ITE} {DFMFileType} {UProgress.dfm}
{ITE} {DFMFileType} {USaveas.dfm}
{ITE} {DFMFileType} {USearchResult.dfm}
{ITE} {DFMFileType} {USelLonLat.dfm}
{ITE} {DFMFileType} {Usettings.dfm}
{ITE} {RCFileType} {SASPlanet_DRC.rc}

{$R 'vcl\DBLOGDLG.dfm' LoginDialog:TForm(Form)}
{$R 'vcl\DBPWDLG.dfm' PasswordDialog:TForm(Form)}
{$R 'u_MarksDb.dfm' DMMarksDb:TDataModule}
{$R 'UAbout.dfm' Fabout:TForm}
{$R 'UAddCategory.dfm' FAddCategory:TForm}
{$R 'UaddLine.dfm' FaddLine:TForm}
{$R 'UaddPoint.dfm' FaddPoint:TForm}
{$R 'UaddPoly.dfm' FAddPoly:TForm}
{$R 'Ubrowser.dfm' Fbrowser:TForm}
{$R 'UEditMap.dfm' FEditMap:TForm}
{$R 'UFDGAvailablePic.dfm' FDGAvailablePic:TForm}
{$R 'UImport.dfm' FImport:TForm}
{$R 'ULogo.dfm' FLogo:TForm}
{$R 'UMarksExplorer.dfm' FMarksExplorer:TForm}
{$R 'Unit1.dfm' Fmain:TForm}
{$R 'Unit2.dfm' FGoTo:TForm}
{$R 'Unit4.dfm' Fprogress2:TForm}
{$R 'UProgress.dfm' FProgress:TForm}
{$R 'USaveas.dfm' Fsaveas:TForm}
{$R 'USearchResult.dfm' FSearchResult:TForm}
{$R 'USelLonLat.dfm' FSelLonLat:TForm}
{$R 'Usettings.dfm' FSettings:TForm}
{$R 'SASPlanet_DRC.res' 'SASPlanet_DRC.rc'}

{$E ENU}

begin
end.