unit u_Datum_Test;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, i_Datum, u_Datum, t_GeoTypes;

type
  // Test methods for class TDatum
  
  TestTDatum = class(TTestCase)
  published
    //procedure TestCalcDist;
    procedure TestCalcFinishPosition;
  end;

implementation

uses
  c_CoordConverter;

//procedure TestTDatum.TestCalcDist;
//var
//  ReturnValue: Double;
//  AFinish: TDoublePoint;
//  AStart: TDoublePoint;
//begin
//  // TODO: Setup method call parameters
//  ReturnValue := FDatum.CalcDist(AStart, AFinish);
//  // TODO: Validate method results
//end;

procedure TestTDatum.TestCalcFinishPosition;
var
  ReturnValue: TDoublePoint;
  ADistance: Double;
  AStart: TDoublePoint;
  VDatum: IDatum;
begin
  VDatum := TDatum.Create(CGELonLatProjectionEPSG, 6378137.0000, 6356752.3142);

  AStart.X := 53.00;
  AStart.Y := 30.00;
  ADistance := 100000; // 100 km

  ReturnValue := VDatum.CalcFinishPosition(AStart, 30, ADistance);

  CheckEquals(ReturnValue.X, 53,775762433053);
  CheckEquals(ReturnValue.Y, 30,7583979041364);
end;

initialization
  RegisterTest(TestTDatum.Suite);

end.

