object frmIntrnalBrowser: TfrmIntrnalBrowser
  Left = 444
  Top = 208
  BorderStyle = bsSizeToolWin
  ClientHeight = 306
  ClientWidth = 554
  Color = clBtnFace
  ParentFont = True
  OldCreateOrder = False
  PopupMode = pmExplicit
  Position = poDefault
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  OnHide = FormHide
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
end
